services:
  mariadb:
    image: mariadb:11.2.2
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - network-1
  
  pma:
    image: phpmyadmin:5.2.1
    container_name: pma
    restart: always
    environment:
      - VIRTUAL_HOST=pma.local
      - VIRTUAL_PORT=80
      - PMA_HOST=mariadb
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - network-1
volumes:
  mariadb-data:

networks:
  network-1:
    external: true

